<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KamarSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        DB::table('kamars')->insert([
            [
                'id_hotel' => 1,
                'nama_kamar' => 'Deluxe Queen',
                'nomor_kamar' => '101',
                'tipe_kamar' => 'Deluxe',
                'harga' => 750000,
                'status_kamar' => true,
                'lantai' => '1',
                'kapasitas' => 2,
                'stok_kamar' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 2,
                'nama_kamar' => 'Family Suite',
                'nomor_kamar' => '201',
                'tipe_kamar' => 'Suite',
                'harga' => 1250000,
                'status_kamar' => true,
                'lantai' => '2',
                'kapasitas' => 4,
                'stok_kamar' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 3,
                'nama_kamar' => 'Ocean View',
                'nomor_kamar' => '10A',
                'tipe_kamar' => 'Deluxe',
                'harga' => 950000,
                'status_kamar' => true,
                'lantai' => '10',
                'kapasitas' => 3,
                'stok_kamar' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 4,
                'nama_kamar' => 'Standard Twin',
                'nomor_kamar' => '05B',
                'tipe_kamar' => 'Standard',
                'harga' => 550000,
                'status_kamar' => true,
                'lantai' => '5',
                'kapasitas' => 2,
                'stok_kamar' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 1,
                'nama_kamar' => 'Executive Suite',
                'nomor_kamar' => '102',
                'tipe_kamar' => 'Suite',
                'harga' => 1450000,
                'status_kamar' => true,
                'lantai' => '2',
                'kapasitas' => 3,
                'stok_kamar' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 1,
                'nama_kamar' => 'Standard Double',
                'nomor_kamar' => '103',
                'tipe_kamar' => 'Standard',
                'harga' => 550000,
                'status_kamar' => true,
                'lantai' => '1',
                'kapasitas' => 2,
                'stok_kamar' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 2,
                'nama_kamar' => 'Deluxe Sea View',
                'nomor_kamar' => '202',
                'tipe_kamar' => 'Deluxe',
                'harga' => 990000,
                'status_kamar' => true,
                'lantai' => '2',
                'kapasitas' => 3,
                'stok_kamar' => 4,
                'created_at' => $now,
                'updated_at' => $now,

            ],
            [
                'id_hotel' => 2,
                'nama_kamar' => 'Standard Garden',
                'nomor_kamar' => '203',
                'tipe_kamar' => 'Standard',
                'harga' => 600000,
                'status_kamar' => true,
                'lantai' => '2',
                'kapasitas' => 2,
                'stok_kamar' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 3,
                'nama_kamar' => 'Mountain Suite',
                'nomor_kamar' => '301',
                'tipe_kamar' => 'Suite',
                'harga' => 1200000,
                'status_kamar' => true,
                'lantai' => '3',
                'kapasitas' => 3,
                'stok_kamar' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 3,
                'nama_kamar' => 'Standard Valley',
                'nomor_kamar' => '303',
                'tipe_kamar' => 'Standard',
                'harga' => 500000,
                'status_kamar' => true,
                'lantai' => '3',
                'kapasitas' => 2,
                'stok_kamar' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 4,
                'nama_kamar' => 'City Executive Suite',
                'nomor_kamar' => '401',
                'tipe_kamar' => 'Suite',
                'harga' => 1400000,
                'status_kamar' => true,
                'lantai' => '4',
                'kapasitas' => 3,
                'stok_kamar' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 4,
                'nama_kamar' => 'City Deluxe King',
                'nomor_kamar' => '402',
                'tipe_kamar' => 'Deluxe',
                'harga' => 900000,
                'status_kamar' => true,
                'lantai' => '4',
                'kapasitas' => 2,
                'stok_kamar' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 5,
                'nama_kamar' => 'Riverside Suite',
                'nomor_kamar' => '501',
                'tipe_kamar' => 'Suite',
                'harga' => 1100000,
                'status_kamar' => true,
                'lantai' => '5',
                'kapasitas' => 3,
                'stok_kamar' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 5,
                'nama_kamar' => 'Riverside Deluxe',
                'nomor_kamar' => '502',
                'tipe_kamar' => 'Deluxe',
                'harga' => 750000,
                'status_kamar' => true,
                'lantai' => '5',
                'kapasitas' => 2,
                'stok_kamar' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 5,
                'nama_kamar' => 'Riverside Standard',
                'nomor_kamar' => '503',
                'tipe_kamar' => 'Standard',
                'harga' => 500000,
                'status_kamar' => true,
                'lantai' => '5',
                'kapasitas' => 2,
                'stok_kamar' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 6,
                'nama_kamar' => 'Heritage Suite',
                'nomor_kamar' => '601',
                'tipe_kamar' => 'Suite',
                'harga' => 1300000,
                'status_kamar' => true,
                'lantai' => '6',
                'kapasitas' => 3,
                'stok_kamar' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 6,
                'nama_kamar' => 'Heritage Deluxe',
                'nomor_kamar' => '602',
                'tipe_kamar' => 'Deluxe',
                'harga' => 850000,
                'status_kamar' => true,
                'lantai' => '6',
                'kapasitas' => 2,
                'stok_kamar' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 6,
                'nama_kamar' => 'Heritage Standard',
                'nomor_kamar' => '603',
                'tipe_kamar' => 'Standard',
                'harga' => 550000,
                'status_kamar' => true,
                'lantai' => '6',
                'kapasitas' => 2,
                'stok_kamar' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 7,
                'nama_kamar' => 'Skyline Suite',
                'nomor_kamar' => '701',
                'tipe_kamar' => 'Suite',
                'harga' => 1500000,
                'status_kamar' => true,
                'lantai' => '7',
                'kapasitas' => 3,
                'stok_kamar' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 7,
                'nama_kamar' => 'Skyline Deluxe',
                'nomor_kamar' => '702',
                'tipe_kamar' => 'Deluxe',
                'harga' => 1000000,
                'status_kamar' => true,
                'lantai' => '7',
                'kapasitas' => 2,
                'stok_kamar' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 7,
                'nama_kamar' => 'Skyline Standard',
                'nomor_kamar' => '703',
                'tipe_kamar' => 'Standard',
                'harga' => 700000,
                'status_kamar' => true,
                'lantai' => '7',
                'kapasitas' => 2,
                'stok_kamar' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 8,
                'nama_kamar' => 'Garden Suite',
                'nomor_kamar' => '801',
                'tipe_kamar' => 'Suite',
                'harga' => 1200000,
                'status_kamar' => true,
                'lantai' => '8',
                'kapasitas' => 3,
                'stok_kamar' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 8,
                'nama_kamar' => 'Garden Deluxe',
                'nomor_kamar' => '802',
                'tipe_kamar' => 'Deluxe',
                'harga' => 850000,
                'status_kamar' => true,
                'lantai' => '8',
                'kapasitas' => 2,
                'stok_kamar' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 8,
                'nama_kamar' => 'Garden Standard',
                'nomor_kamar' => '803',
                'tipe_kamar' => 'Standard',
                'harga' => 600000,
                'status_kamar' => true,
                'lantai' => '8',
                'kapasitas' => 2,
                'stok_kamar' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 9,
                'nama_kamar' => 'Hills Suite',
                'nomor_kamar' => '901',
                'tipe_kamar' => 'Suite',
                'harga' => 1250000,
                'status_kamar' => true,
                'lantai' => '9',
                'kapasitas' => 3,
                'stok_kamar' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 9,
                'nama_kamar' => 'Hills Deluxe',
                'nomor_kamar' => '902',
                'tipe_kamar' => 'Deluxe',
                'harga' => 900000,
                'status_kamar' => true,
                'lantai' => '9',
                'kapasitas' => 2,
                'stok_kamar' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 9,
                'nama_kamar' => 'Hills Standard',
                'nomor_kamar' => '903',
                'tipe_kamar' => 'Standard',
                'harga' => 650000,
                'status_kamar' => true,
                'lantai' => '9',
                'kapasitas' => 2,
                'stok_kamar' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 10,
                'nama_kamar' => 'Convention Suite',
                'nomor_kamar' => '1001',
                'tipe_kamar' => 'Suite',
                'harga' => 1350000,
                'status_kamar' => true,
                'lantai' => '10',
                'kapasitas' => 3,
                'stok_kamar' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 10,
                'nama_kamar' => 'Convention Deluxe',
                'nomor_kamar' => '1002',
                'tipe_kamar' => 'Deluxe',
                'harga' => 950000,
                'status_kamar' => true,
                'lantai' => '10',
                'kapasitas' => 2,
                'stok_kamar' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 10,
                'nama_kamar' => 'Convention Standard',
                'nomor_kamar' => '1003',
                'tipe_kamar' => 'Standard',
                'harga' => 650000,
                'status_kamar' => true,
                'lantai' => '10',
                'kapasitas' => 2,
                'stok_kamar' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 11,
                'nama_kamar' => 'Boutique Suite',
                'nomor_kamar' => '1101',
                'tipe_kamar' => 'Suite',
                'harga' => 1150000,
                'status_kamar' => true,
                'lantai' => '11',
                'kapasitas' => 3,
                'stok_kamar' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 11,
                'nama_kamar' => 'Boutique Deluxe',
                'nomor_kamar' => '1102',
                'tipe_kamar' => 'Deluxe',
                'harga' => 820000,
                'status_kamar' => true,
                'lantai' => '11',
                'kapasitas' => 2,
                'stok_kamar' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 11,
                'nama_kamar' => 'Boutique Standard',
                'nomor_kamar' => '1103',
                'tipe_kamar' => 'Standard',
                'harga' => 580000,
                'status_kamar' => true,
                'lantai' => '11',
                'kapasitas' => 2,
                'stok_kamar' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 12,
                'nama_kamar' => 'Lakeview Suite',
                'nomor_kamar' => '1201',
                'tipe_kamar' => 'Suite',
                'harga' => 1400000,
                'status_kamar' => true,
                'lantai' => '12',
                'kapasitas' => 3,
                'stok_kamar' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 12,
                'nama_kamar' => 'Lakeview Deluxe',
                'nomor_kamar' => '1202',
                'tipe_kamar' => 'Deluxe',
                'harga' => 1000000,
                'status_kamar' => true,
                'lantai' => '12',
                'kapasitas' => 2,
                'stok_kamar' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 12,
                'nama_kamar' => 'Lakeview Standard',
                'nomor_kamar' => '1203',
                'tipe_kamar' => 'Standard',
                'harga' => 700000,
                'status_kamar' => true,
                'lantai' => '12',
                'kapasitas' => 2,
                'stok_kamar' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 13,
                'nama_kamar' => 'Airport Suite',
                'nomor_kamar' => '1301',
                'tipe_kamar' => 'Suite',
                'harga' => 1100000,
                'status_kamar' => true,
                'lantai' => '13',
                'kapasitas' => 3,
                'stok_kamar' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 13,
                'nama_kamar' => 'Airport Deluxe',
                'nomor_kamar' => '1302',
                'tipe_kamar' => 'Deluxe',
                'harga' => 850000,
                'status_kamar' => true,
                'lantai' => '13',
                'kapasitas' => 2,
                'stok_kamar' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 13,
                'nama_kamar' => 'Airport Standard',
                'nomor_kamar' => '1303',
                'tipe_kamar' => 'Standard',
                'harga' => 600000,
                'status_kamar' => true,
                'lantai' => '13',
                'kapasitas' => 2,
                'stok_kamar' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 14,
                'nama_kamar' => 'Eco Lodge Suite',
                'nomor_kamar' => '1401',
                'tipe_kamar' => 'Suite',
                'harga' => 1200000,
                'status_kamar' => true,
                'lantai' => '14',
                'kapasitas' => 3,
                'stok_kamar' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 14,
                'nama_kamar' => 'Eco Lodge Deluxe',
                'nomor_kamar' => '1402',
                'tipe_kamar' => 'Deluxe',
                'harga' => 900000,
                'status_kamar' => true,
                'lantai' => '14',
                'kapasitas' => 2,
                'stok_kamar' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id_hotel' => 14,
                'nama_kamar' => 'Eco Lodge Standard',
                'nomor_kamar' => '1403',
                'tipe_kamar' => 'Standard',
                'harga' => 650000,
                'status_kamar' => true,
                'lantai' => '14',
                'kapasitas' => 2,
                'stok_kamar' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

    }
}
